apiVersion: v1
kind: Service
metadata:
  name: time-tracker
  labels:
    app: time-tracker
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: time-tracker